name: Bug Report
description: Report a bug or issue
title: "[BUG]: "
labels: ["triage-required"]
body:
  - type: markdown
    attributes:
      value: |
        Hi there,
        Thank you for opening an issue. Please be aware that this is a Community Project from Sonatype, and is not officially supported by Sonatype.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: sonatypeiq-version
    attributes:
      label: Sonatype IQ Server Version
      description: Version of the Sonatype IQ Server you are running Terraform against
    validations:
      required: true

  - type: textarea
    id: terraform-version
    attributes:
      label: Terraform Version
      description: Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
    validations:
      required: true

  - type: textarea
    id: affected-resources
    attributes:
      label: Affected Resource(s)
      description: |
        Please list the resources as a list. If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
      placeholder: |
        e.g.
         - sonatypeiq_application
    validations:
      required: true

  - type: textarea
    id: terraform-configuration-files
    attributes:
      label: Terraform Configuration Files
      render: hcl
      description: |
        Please copy and paste any relevant configration files. This will be automatically formatted into code, so no need for backticks.
        Please check your configuration before submission to ensure sensitive information is redacted.
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please list the steps required to reproduce the issue.
      placeholder: |
        ```
        $ terraform apply
        ```
    validations:
      required: false

  - type: textarea
    id: debug-output
    attributes:
      label: Debug Output
      description: |
        Please copy and paste any relevant debug output. This will be automatically formatted into code, so no need for backticks.
        Please check your logs before submission to ensure sensitive information is redacted.
      render: shell
    validations:
      required: false

  - type: textarea
    id: panic-output
    attributes:
      label: Panic Output
      description: |
        Please copy and paste any relevant panic output. This will be automatically formatted into code, so no need for backticks.
        Please check your logs before submission to ensure sensitive information is redacted.
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/sonatype-nexus-community/terraform-provider-sonatypeiq/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true